import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { apiFetch } from "@/lib/api";
import { Field, inputClass, useAction, states, types, cancellations, emailStates, money, date, downloadFiscal } from "./shared";

interface Document {
  id: string; number: string | null; documentType: string; environment: string; status: string; cancellationStatus: string; total: string; issueDate: string; accessKey: string | null; authorizationNumber: string | null; authorizedAt: string | null; lastMessage: string | null; buyerWarning: string | null; recipientEmail: string | null; dispatchOrderId: string | null;
  snapshot: { issuer: { legalName: string; ruc: string }; buyer: { name: string; identification: string; identificationType: string; address: string; email: string }; paymentCode: string; creditDays: number; transport?: { startDate: string; endDate: string }; lines: { itemId: string; code: string; description: string; quantity: number; unitPrice: string; ivaRate: string }[] };
  events: { id: string; message: string; createdAt: string }[]; deliveries: { id: string; recipient: string; status: string; createdAt: string; error?: string }[];
  corrections: { id: string; number: string | null; status: string; total: string }[]; original?: { id: string; number: string };
}
function DocumentActions({ doc }: { doc: Document }) {
  const action = useAction(), navigate = useNavigate();
  const [buyer, setBuyer] = useState({ ...doc.snapshot.buyer, email: doc.snapshot.buyer.email ?? "" });
  const [paymentCode, setPaymentCode] = useState(doc.snapshot.paymentCode || "");
  const isoDate = (value?: string) => value ? value.split("/").reverse().join("-") : "";
  const [transport, setTransport] = useState({ startDate: isoDate(doc.snapshot.transport?.startDate), endDate: isoDate(doc.snapshot.transport?.endDate) });
  const [recipient, setRecipient] = useState(doc.recipientEmail ?? "");
  const [creditOpen, setCreditOpen] = useState(false), [reason, setReason] = useState("");
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [evidence, setEvidence] = useState(""), [cancellation, setCancellation] = useState("REQUESTED");
  return <div className="space-y-5">
    {doc.status === "REJECTED" && <Button variant="outline" disabled={action.isPending} onClick={() => action.mutate({ path: `/fiscal-documents/${doc.id}/correct-rejected` })}>Consultar SRI y habilitar corrección</Button>}
    {doc.status === "DRAFT" && <section className="space-y-4 rounded-md border p-5"><h2 className="font-semibold">Revisar y emitir</h2>
      {doc.buyerWarning && <p role="alert" className="rounded-md border border-amber-500/50 bg-amber-500/10 p-3 text-sm">{doc.buyerWarning}</p>}
      {doc.documentType !== "04" && <form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ path: `/fiscal-documents/${doc.id}/buyer`, method: "PATCH", data: buyer }); }}><div className="grid gap-3 md:grid-cols-2">{([["name", "Nombre / razón social"], ["identification", "Identificación"], ["address", "Dirección"], ["email", "Correo (opcional)"]] as const).map(([key, label]) => <Field label={label} key={key}><input required={key !== "email"} className={inputClass} type={key === "email" ? "email" : "text"} value={buyer[key]} onChange={e => setBuyer({ ...buyer, [key]: e.target.value })} /></Field>)}<Field label="Tipo de identificación"><select className={inputClass} value={buyer.identificationType} onChange={e => setBuyer({ ...buyer, identificationType: e.target.value })}><option value="04">RUC</option><option value="05">Cédula</option><option value="06">Pasaporte</option></select></Field></div><Button variant="outline" disabled={action.isPending}>Guardar datos del comprador</Button></form>}
      {doc.documentType === "06" && <form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ path: `/fiscal-documents/${doc.id}/transport`, method: "PATCH", data: transport }); }}><p className="text-sm text-muted-foreground">El SRI rechaza la guía si el inicio del traslado es anterior a su fecha de emisión.</p><div className="grid gap-3 md:grid-cols-2"><Field label="Inicio del traslado"><input required type="date" className={inputClass} value={transport.startDate} onChange={e => setTransport({ ...transport, startDate: e.target.value })} /></Field><Field label="Fin del traslado"><input required type="date" className={inputClass} min={transport.startDate} value={transport.endDate} onChange={e => setTransport({ ...transport, endDate: e.target.value })} /></Field></div><Button variant="outline" disabled={action.isPending}>Guardar fechas del traslado</Button></form>}
      {doc.documentType === "01" && <Field label="Medio de pago (independiente del plazo de crédito)"><select className={inputClass} value={paymentCode} onChange={e => setPaymentCode(e.target.value)}><option value="">Seleccionar</option><option value="01">Sin utilización del sistema financiero</option><option value="20">Otros con utilización del sistema financiero / transferencia</option><option value="16">Tarjeta de débito</option><option value="19">Tarjeta de crédito</option><option value="15">Compensación de deudas</option><option value="17">Dinero electrónico</option><option value="18">Tarjeta prepago</option><option value="21">Endoso de títulos</option></select></Field>}
      <p className="text-sm text-muted-foreground">Al emitir se asigna la numeración, se firma el documento y se transmite al SRI. Los datos guardados quedan congelados.</p>
      <div className="flex flex-wrap gap-2"><Button disabled={action.isPending || (doc.documentType === "01" && !paymentCode)} onClick={() => action.mutate({ path: `/fiscal-documents/${doc.id}/issue`, data: { paymentCode } })}>{action.isPending ? "Procesando…" : `Emitir en ${doc.environment === "1" ? "pruebas" : "producción"}`}</Button>{doc.documentType === "04" && <Button variant="outline" disabled={action.isPending} onClick={() => action.mutate({ path: `/fiscal-documents/${doc.id}/void-draft` })}>Descartar borrador de nota</Button>}</div>
    </section>}
    {["QUEUED", "WAITING", "RECEIVED"].includes(doc.status) && <Button variant="outline" disabled={action.isPending} onClick={() => action.mutate({ path: `/fiscal-documents/${doc.id}/retry` })}>Consultar / reintentar la misma clave</Button>}
    {doc.status === "AUTHORIZED" && <section className="space-y-3 rounded-md border p-5"><h2 className="font-semibold">Enviar comprobante</h2><form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); action.mutate({ path: `/fiscal-documents/${doc.id}/email`, data: { recipient } }); }}><Field label="Destinatario"><input className={inputClass} type="email" required value={recipient} onChange={e => setRecipient(e.target.value)} /></Field><Button disabled={action.isPending}>Enviar XML y RIDE</Button></form></section>}
    {doc.status === "AUTHORIZED" && doc.documentType === "01" && doc.cancellationStatus === "NONE" && <section className="space-y-3 rounded-md border p-5"><Button variant="outline" onClick={() => setCreditOpen(!creditOpen)}>Crear nota de crédito</Button>{creditOpen && <form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ path: `/fiscal-documents/${doc.id}/credit-note`, data: { reason, lines: Object.entries(quantities).filter(([, q]) => q > 0).map(([itemId, quantity]) => ({ itemId, quantity })) } }, { onSuccess: result => navigate(`/billing/${result.id}`) }); }}><Field label="Motivo"><input className={inputClass} required value={reason} onChange={e => setReason(e.target.value)} /></Field>{doc.snapshot.lines.map(l => <Field key={l.itemId} label={`${l.description} · Unidades originales: ${l.quantity}`}><input className={inputClass} type="number" min={0} max={l.quantity} value={quantities[l.itemId] ?? 0} onChange={e => setQuantities({ ...quantities, [l.itemId]: Number(e.target.value) })} /></Field>)}<p className="text-sm text-muted-foreground">Se conservarán los precios e impuestos originales y se comprobarán las notas anteriores.</p><Button disabled={action.isPending || !Object.values(quantities).some(q => q > 0)}>Preparar nota</Button></form>}</section>}
    {doc.status === "AUTHORIZED" && doc.cancellationStatus !== "CONFIRMED" && <details className="rounded-md border p-5"><summary className="cursor-pointer font-medium">Registrar trámite de anulación realizado en el SRI</summary><p className="my-3 text-sm">Esta opción registra el trámite realizado en el portal. No envía una solicitud de anulación al SRI.</p><form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ path: `/fiscal-documents/${doc.id}/cancellation`, data: { status: cancellation, evidence } }); }}><Field label="Resultado del trámite"><select className={inputClass} value={cancellation} onChange={e => setCancellation(e.target.value)}><option value="REQUESTED">Solicitud presentada</option><option value="CONFIRMED" disabled={doc.cancellationStatus !== "REQUESTED"}>Confirmación obtenida en el SRI</option><option value="REJECTED" disabled={doc.cancellationStatus !== "REQUESTED"}>Solicitud rechazada</option></select></Field><Field label="Referencia y evidencia del trámite"><textarea className="rounded-md border p-3" required minLength={10} value={evidence} onChange={e => setEvidence(e.target.value)} /></Field><Button disabled={action.isPending}>Registrar resultado del portal</Button></form></details>}
  </div>;
}
export function FiscalDocumentDetailPage() {
  const { id } = useParams();
  const query = useQuery({ queryKey: ["fiscal", "document", id], queryFn: () => apiFetch<Document>(`/fiscal-documents/${id}`), refetchInterval: 10000 });
  if (query.isLoading) return <p>Cargando comprobante…</p>;
  if (query.error || !query.data) return <p role="alert">{query.error?.message ?? "No encontrado"}</p>;
  const doc = query.data;
  return <div className="space-y-5"><Link className="text-sm underline" to="/billing">Volver a comprobantes</Link><div><h1 className="text-2xl font-semibold">{types[doc.documentType]} · {doc.number ?? "Borrador"}</h1><p className="text-sm">{doc.snapshot.issuer.legalName} · RUC {doc.snapshot.issuer.ruc}</p><p className="text-sm">{doc.environment === "1" ? "PRUEBAS · Sin validez tributaria" : "PRODUCCIÓN"} · {states[doc.status]} · {cancellations[doc.cancellationStatus]}</p></div>
    {doc.lastMessage && <p role="status" className="rounded-md bg-muted p-3 text-sm">{doc.lastMessage}</p>}
    <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => downloadFiscal(doc.id, "pdf", doc.number ?? "borrador")}>{doc.status === "AUTHORIZED" ? "Descargar RIDE" : "Vista previa PDF"}</Button><Button variant="outline" disabled={doc.status !== "AUTHORIZED"} onClick={() => downloadFiscal(doc.id, "xml", doc.number!)}>XML autorizado</Button>{doc.dispatchOrderId && <Button variant="outline" asChild><Link to={`/dispatch-orders/${doc.dispatchOrderId}`}>Ver despacho</Link></Button>}</div>
    <section className="space-y-2 rounded-md border p-4 text-sm"><p>Fecha: {date(doc.issueDate)}</p><p>Comprador: {doc.snapshot.buyer.name} · {doc.snapshot.buyer.identification}</p><p>Dirección: {doc.snapshot.buyer.address || "Pendiente"}</p>{doc.accessKey && <p className="break-all">Clave de acceso: {doc.accessKey}</p>}{doc.authorizationNumber && <p className="break-all">Autorización: {doc.authorizationNumber}</p>}{doc.original && <p>Factura original: <Link className="underline" to={`/billing/${doc.original.id}`}>{doc.original.number}</Link></p>}</section>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Producto</th><th>Cantidad</th><th>Precio sin IVA</th><th>IVA</th></tr></thead><tbody>{doc.snapshot.lines.map(l => <tr className="border-b" key={l.itemId}><td className="p-2">{l.code} · {l.description}</td><td>{l.quantity}</td><td>{money(l.unitPrice)}</td><td>{l.ivaRate}%</td></tr>)}</tbody></table></div>{doc.documentType !== "06" && <p className="text-right font-semibold">Total: {money(doc.total)}</p>}
    <DocumentActions key={`${doc.id}:${doc.status}`} doc={doc} />
    {!!doc.corrections.length && <section><h2 className="font-semibold">Notas relacionadas</h2>{doc.corrections.map(c => <p className="text-sm" key={c.id}><Link className="underline" to={`/billing/${c.id}`}>{c.number ?? "Borrador"}</Link> · {states[c.status]} · {money(c.total)}</p>)}</section>}
    <section className="space-y-2"><h2 className="font-semibold">Historial</h2>{doc.events.map(e => <p className="text-sm" key={e.id}>{new Date(e.createdAt).toLocaleString("es-EC")} · {e.message}</p>)}</section><section className="space-y-2"><h2 className="font-semibold">Envíos por correo</h2>{doc.deliveries.map(d => <p key={d.id} className="text-sm">{date(d.createdAt)} · {d.recipient} · {emailStates[d.status]} {d.error}</p>)}{!doc.deliveries.length && <p className="text-sm text-muted-foreground">Sin envíos registrados.</p>}</section>
  </div>;
}
