import { z } from "zod";

// Los códigos (SKU, referencias) siempre los genera el sistema para que sean
// uniformes: si el cliente intenta enviar uno se rechaza con un mensaje claro
// en vez de ignorarlo en silencio.
export const autoGenerated = (label: string) =>
  z.undefined({ invalid_type_error: `${label} se genera automáticamente; no lo envíes` }).optional();
