import { ProductStatus } from "@prisma/client";
import { z } from "zod";
import { IVA_CODES } from "../../lib/ivaRates";
import { autoGenerated } from "../../lib/autoCode.schema";

// SKU automático: <código de la categoría>-<correlativo>, ej. COC-0001.
export const createProductSchema = z.object({
  sku: autoGenerated("El SKU"),
  name: z.string().min(1, "El nombre es obligatorio").max(200),
  description: z.string().max(2000).optional(),
  model: z.string().max(100).optional(),
  barcode: z.string().max(50).optional(),
  categoryId: z.string().min(1, "La categoría es obligatoria"),
  subcategoryId: z.string().min(1).optional(),
  brandId: z.string().min(1).optional(),
  // Tarifa de IVA (precios sin IVA). Sin valor, el producto nace con la general.
  ivaCode: z.enum(IVA_CODES).optional(),
});

// El SKU no cambia nunca (tampoco al cambiar de categoría): ya puede estar impreso.
export const updateProductSchema = z.object({
  sku: autoGenerated("El SKU"),
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(2000).nullable().optional(),
  model: z.string().max(100).nullable().optional(),
  barcode: z.string().max(50).nullable().optional(),
  status: z.nativeEnum(ProductStatus).optional(),
  categoryId: z.string().min(1).optional(),
  subcategoryId: z.string().min(1).nullable().optional(),
  brandId: z.string().min(1).nullable().optional(),
  ivaCode: z.enum(IVA_CODES).optional(),
});

export const listProductsQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
  categoryId: z.string().optional(),
  subcategoryId: z.string().optional(),
  status: z.nativeEnum(ProductStatus).optional(),
  brandId: z.string().optional(),
  q: z.string().optional(),
});
